kind: pipeline
name: default
steps:
#  - name: authenticate
#    image: robertstettner/drone-mvn-auth
#    settings:
#      servers:
#        - id: central
#          username: $${env.ARTIFACTORY_USER}
#          password: $${env.ARTIFACTORY_PASSWORD}
#        - id: snapshots
#          username: $${env.ARTIFACTORY_USER}
#          password: $${env.ARTIFACTORY_PASSWORD}
  - name: build
    image: 'maven:3.6.3-jdk-8-slim'
#    environment:
#      ARTIFACTORY_USER:
#        from_secret: ARTIFACTORY_USER
#      ARTIFACTORY_PASSWORD:
#        from_secret: ARTIFACTORY_PASSWORD
    commands:
      - mvn clean install -B -U
  - name: notify status
    image: drillster/drone-email
    settings:
      host: smtp.ionos.de
      port: 587
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      from: build@mygamma.io
      recipients:
        - sudarshan.bhide@embold.io
        - nilesh.virkar@embold.io
    when:
      status: [ changed, failure, success ]
