package io.embold.scan;

public enum Package {
    CORE, JAVA, CPP, C_SHARP, PYTHON, JAVASCRIPT, TYPESCRIPT, GO, SCALA, OBJECTIVE_C, KOTLIN, WEB, PHP, RUST, SOLIDITY, MULTI, SQL, SWIFT, RUBY, HTML, APEX, CSS
}
